# JTSDK-QT Tool-Chain File for WSJTX
# Part of the JTSDK v2.0.0 Project
# NOTE: WSKT-X uses Hamlib3, not Hamlib2
SET (CMAKE_SYSTEM_NAME Windows)
SET (BASED C:/JTSDK)
SET (ASCIIDOC C:/JTSDK/asciidoc)
SET (PYTHON27 C:/JTSDK/python27)
SET (QTDIR C:/JTSDK/qt5/5.2.1/mingw48_32)
SET (HAMLIB C:/JTSDK/hamlib3)
SET (FFTW C:/JTSDK/fftw3f)
SET (CMAKE_PREFIX_PATH ${PYTHON27} ${ASCIIDOC} ${QTDIR} ${FFTW} ${HAMLIB} ${HAMLIB}/bin)
SET (CMAKE_FIND_ROOT_PATH ${BASED})
SET (CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET (CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
SET (CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
